<a href="https://colab.research.google.com/github/jayarnim/M1-DeepLearning/blob/main/skills/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# 텐서의 이해

<p align="center"><img src="https://user-images.githubusercontent.com/116495744/228464597-fac5d8dc-6d04-4874-9c76-30155fb88035.png" width=100%/></p>

- **정의** : 데이터를 저장하기 위한 선형대수 형태의 컨테이너

# 속성

In [ ]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


## 축의 갯수

- 관측치 축(Sample Axis) : 첫 번째 축으로서 텐서에 포함되어 있는 관측치 갯수

In [ ]:
train_images.ndim

3

## 크기

- **시계열** : `(sample, timestep, feature)`
- **이미지** : `(sample, height, width, channel)`
- **동영상** : `(sample, frames, height, width, channel)`

In [ ]:
train_images.shape

(60000, 28, 28)

## 자료형

- **정수형** : `tf.int64`, `tf.int32`, `tf.int16`, `tf.int8`
- **실수형** : `tf.float64`, `tf.float32`, `tf.float16`
- **문자열** : `tf.string`

In [ ]:
train_images.dtype

dtype('uint8')

# 상수 텐서

## 상수 텐서

In [ ]:
value_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

x = tf.constant(
    value = value_list,
    dtype = tf.float32,
    shape = (3,3),
    name = "const_tensor"
    )

print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [ ]:
# 상수 텐서는 원소에 대하여 변경 불가능한 자료구조임
# x[2,2] = 10

TypeError: ignored

## 특수한 텐서

### 0텐서

In [ ]:
x = tf.zeros(
    shape = (10,10)
    )

print(x)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


### 1텐서

In [ ]:
x = tf.ones(
    shape = (10,10)
    )
print(x)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


### 랜덤 텐서

In [ ]:
# 평균이 0이고 표준 편차가 1인 정규 분포에서 뽑은 난수 값으로 생성한 텐서
x = tf.random.normal(
    shape = (2,2),
    mean = 0,
    stddev = 1
    )

print(x)

tf.Tensor(
[[ 2.0202007   0.8895326 ]
 [-0.63770664  0.6068259 ]], shape=(2, 2), dtype=float32)


In [ ]:
# 최소값이 0이고 최대값이 1인 균등 분포에서 뽑은 난수 값으로 생성한 텐서
x = tf.random.uniform(
    shape = (2,2),
    minval = 0,
    maxval = 1
    )

print(x)

tf.Tensor(
[[0.8735938  0.05168533]
 [0.51129544 0.9813677 ]], shape=(2, 2), dtype=float32)


# 변수 텐서

## 변수 텐서

In [ ]:
x = tf.Variable(
    initial_value = tf.random.normal(shape = (3,1))
    )

print(x)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.5288062 ],
       [-0.7936362 ],
       [-0.67070675]], dtype=float32)>


## 원소 갱신하기

In [ ]:
# 값을 갱신할 수 있음
x[0,0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 3.        ],
       [-0.7936362 ],
       [-0.67070675]], dtype=float32)>

In [ ]:
# +=
x.assign_add(
    tf.ones(shape = (3,1))
    )

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.        ],
       [0.2063638 ],
       [0.32929325]], dtype=float32)>

In [ ]:
# -=
x.assign_sub(
    tf.ones(shape = (3,1))
    )

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 3.        ],
       [-0.7936362 ],
       [-0.67070675]], dtype=float32)>

# 변환

In [ ]:
x = tf.Variable(
    initial_value = tf.random.normal(shape = (3,4,2))
    )

## 자료형 변환

In [ ]:
x.dtype

tf.float32

In [ ]:
x = tf.cast(
    x = x,
    dtype = tf.float64
    )

In [ ]:
x.dtype

tf.float64

## 크기 변환

In [ ]:
tf.reshape(
    tensor = x,
    shape = (4,2,3)
    )

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[ 0.9430902 , -0.41770342,  0.41375807],
        [-0.2311434 ,  2.0530436 ,  2.0826113 ]],

       [[-0.5347682 , -0.9913871 , -2.4695716 ],
        [-0.8565756 , -2.3890352 , -0.32607433]],

       [[-0.08985647,  0.39682317,  0.5490823 ],
        [ 0.13943157, -1.1810787 , -0.00457868]],

       [[-0.88585865, -1.6687293 ,  0.4365611 ],
        [ 1.1611979 , -3.2304447 , -0.43596703]]], dtype=float32)>

## 전치

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.9430902 , -2.4695716 , -1.1810787 ],
        [ 0.41375807, -2.3890352 , -0.88585865],
        [ 2.0530436 , -0.08985647,  0.4365611 ],
        [-0.5347682 ,  0.5490823 , -3.2304447 ]],

       [[-0.41770342, -0.8565756 , -0.00457868],
        [-0.2311434 , -0.32607433, -1.6687293 ],
        [ 2.0826113 ,  0.39682317,  1.1611979 ],
        [-0.9913871 ,  0.13943157, -0.43596703]]], dtype=float32)>

In [ ]:
tf.transpose(
    x,
    perm = (0,2,1)
    )

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[ 0.9430902 ,  0.41375807,  2.0530436 , -0.5347682 ],
        [-0.41770342, -0.2311434 ,  2.0826113 , -0.9913871 ]],

       [[-2.4695716 , -2.3890352 , -0.08985647,  0.5490823 ],
        [-0.8565756 , -0.32607433,  0.39682317,  0.13943157]],

       [[-1.1810787 , -0.88585865,  0.4365611 , -3.2304447 ],
        [-0.00457868, -1.6687293 ,  1.1611979 , -0.43596703]]],
      dtype=float32)>

# 연산

In [ ]:
x = tf.Variable(
    initial_value = tf.random.normal(shape = (3,3))
    )

y = tf.Variable(
    initial_value = tf.random.normal(shape = (3,3))
    )

z = tf.Variable(
    initial_value = [[1.,1.,1.]]
    )

## 덧셈과 뺄셈

In [ ]:
tf.add(x, y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.7071117 ,  1.165798  ,  2.227912  ],
       [ 0.9599832 , -0.28301245, -1.0775944 ],
       [-2.148121  ,  1.5105977 , -0.31958118]], dtype=float32)>

In [ ]:
tf.subtract(x, y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.65363204, -0.9392159 ,  0.11744046],
       [ 4.146922  , -1.7127249 ,  1.7348319 ],
       [-0.25205845,  1.2110729 ,  0.6548947 ]], dtype=float32)>

## 점곱

In [ ]:
tf.matmul(x, y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.67051077, -0.98574007, -1.9762542 ],
       [-0.0664728 ,  2.023409  ,  3.9375951 ],
       [-1.6952584 , -0.26519257, -3.2616909 ]], dtype=float32)>

## 자승과 자승근

In [ ]:
tf.square(x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.3932778 , 0.01283485, 1.3751695 ],
       [6.5201206 , 0.99574196, 0.10799027],
       [1.4402156 , 1.8518728 , 0.0281088 ]], dtype=float32)>

In [ ]:
tf.sqrt(x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[       nan, 0.33658728, 1.0829017 ],
       [1.5979527 ,        nan, 0.57325274],
       [       nan, 1.1665485 , 0.40945914]], dtype=float32)>

## 브로드캐스팅

<p align="center"><img alt="브로드캐스팅" src="https://github.com/jayarnim/jayarnim/assets/116495744/0dfee6de-9e31-4871-9375-ede5e57ee276" width=100%></p>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.26896673,  1.0450807 ,  1.5663651 ],
       [ 0.5709398 , -0.24528983, -1.4665773 ],
       [ 1.4563224 , -1.4952632 , -0.2827511 ]], dtype=float32)>

In [ ]:
z

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [ ]:
tf.subtract(x,z)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.73103327,  0.04508066,  0.5663651 ],
       [-0.42906022, -1.2452898 , -2.4665773 ],
       [ 0.45632243, -2.495263  , -1.2827511 ]], dtype=float32)>