<a href="https://colab.research.google.com/github/jayarnim/M1-DeepLearning/blob/main/skills/2_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Layer

In [2]:
class SimpleDense(Layer):

    # 생성자
    def __init__(self, units, activation=None):
        # tensorflow.keras.layers.Layer 필드 상속
        super().__init__()
        # attribute 노드 갯수 정의
        self.units = units
        # attribute 활성화 함수 정의
        self.activation = activation

    # 클래스의 함수화
    # 층 호환(Layer Compatibility)을 위한 자동 크기 추론
    def __call__(self, inputs):
        if not self.built:
            self.build(inputs.shape)
            self.built = True
        return self.call(inputs)

    # 초기 상태
    def build(self, input_shape):
        # 속성 갯수를 입력값으로 정의
        input_dim = input_shape[-1]
        # 가중치 정의
        self.W = self.add_weight(
            shape = (input_dim, self.units),
            initializer = "random_normal"
            )
        # 편향 정의
        self.b = self.add_weight(
            shape = (self.units,),
            initializer = "zeros"
            )

    # 순전파 연산
    def call(self, inputs):
        # 순입력 함수로 계산한 값
        y = tf.matmul(inputs, self.W) + self.b
        # 활성화 함수로 계산한 값
        if self.activation is not None:
            y = self.activation(y)
        return y

    # 가중치(self.W) 및 편향(self.b)을 원소로 가지는 weights 를 필드로 추가
    @property
    def weights(self):
        return [self.W, self.b]

In [3]:
input_tensor = tf.ones(shape = (2, 28*28))

In [4]:
# init
my_dense = SimpleDense(units = 32, activation = tf.nn.relu)

In [5]:
# __call__
output_tensor = my_dense(input_tensor)

In [6]:
my_dense.weights

[<tf.Variable 'Variable:0' shape=(784, 32) dtype=float32, numpy=
 array([[-0.05473579, -0.00476685,  0.02139034, ..., -0.02768694,
          0.13078451, -0.01606729],
        [-0.03461669, -0.16855772,  0.00591633, ..., -0.04401868,
          0.09141424, -0.09754901],
        [-0.08468332, -0.01564325, -0.0432804 , ...,  0.08998315,
          0.0107043 ,  0.05905263],
        ...,
        [-0.0042083 ,  0.0248778 , -0.02648951, ..., -0.11246993,
          0.05804367, -0.05633357],
        [-0.03949193, -0.00293818,  0.00723151, ...,  0.08712145,
         -0.04007688, -0.0329682 ],
        [-0.01834183,  0.08040272, -0.00564949, ...,  0.03132436,
         -0.07284755,  0.04250565]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(32,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>]

In [7]:
output_tensor

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[0.        , 0.5701773 , 0.        , 0.        , 0.7748363 ,
        1.079584  , 0.        , 0.        , 0.5643964 , 0.68122816,
        3.047016  , 0.        , 0.        , 0.21870418, 1.5347699 ,
        0.02159846, 0.        , 0.        , 0.        , 0.40891773,
        0.29836527, 3.1398964 , 1.0893886 , 0.        , 0.        ,
        1.4530611 , 0.8696098 , 0.        , 0.        , 0.        ,
        0.        , 0.9624073 ],
       [0.        , 0.5701773 , 0.        , 0.        , 0.7748363 ,
        1.079584  , 0.        , 0.        , 0.5643964 , 0.68122816,
        3.047016  , 0.        , 0.        , 0.21870418, 1.5347699 ,
        0.02159846, 0.        , 0.        , 0.        , 0.40891773,
        0.29836527, 3.1398964 , 1.0893886 , 0.        , 0.        ,
        1.4530611 , 0.8696098 , 0.        , 0.        , 0.        ,
        0.        , 0.9624073 ]], dtype=float32)>